### PR TITLE
New release v2.2.0

### PR DESCRIPTION
**Pull request by almarklein**

### CODE REVIEW

**Comment by jakirkham** [comment]
Is the file extension still `.zip` or is it `.tar.gz`?

**Comment by almarklein** [comment]
Ah, its `.tar.gz` now, distutils changed?

**Comment by almarklein** [comment]
@jakirkham its scary how fast you are, given that there are so many projects on conda-forge. I'm going to assume that you're a bot :)

**Comment by jakirkham** [comment]
I don't think so. If you are doing `python setup.py sdist upload`, it will make the archive `.tar.gz`.

**Comment by jakirkham** [comment]
😆 Nah. Just have a really good notification system.

**Comment by almarklein** [comment]
> If you are doing `python setup.py sdist upload`, it will make the archive .tar.gz.

IIRC on Windows that would produce a `.zip`. Anyway, whatever works.

**Comment by jakirkham** [comment]
Ah ok. I have not tried releasing on Windows. So wouldn't know.

**Pull request merged**
